
spring.datasource.url=jdbc:postgresql://localhost:5432/grind90_db
spring.datasource.username=postgres
spring.datasource.password=rohit1229


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rohitkumbhar1229@gmail.com
spring.mail.password=yqikskwghixgrodz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

twilio.account.sid=${TWILIO_SID}
twilio.auth.token=${TWILIO_TOKEN}
twilio.whatsapp.number=${TWILIO_NUMBER}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
gemini.api.key=${GEMINI_API_KEY}

spring.devtools.restart.enabled=false